development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
# production:
#   server: "http://fsrvrproduction.herokuapp.com/faye"
#   secret_token: "6ec326f365aaf93e3d7d331489544eca3709f1a10c11cac2f9c112ef8c1ee1e8"
#   signature_expiration: 83600 # one day
staging:
  server: "http://fayesrvr.herokuapp.com/faye"
  secret_token: "4b79c3038b0a7ecb714c696c0cabc7071534eb21cfccbb444b9119a26db01bff"
  signature_expiration: 3600 # one hour

production:
  server: "http://fayesrvr.herokuapp.com/faye"
  secret_token: "4b79c3038b0a7ecb714c696c0cabc7071534eb21cfccbb444b9119a26db01bff"
  signature_expiration: 3600 # one hour


  #PRODUCTION FAYE: : http://fsrvrproduction.herokuapp.com/faye
  #STAGING FAYE:  http://fayesrvr.herokuapp.com/faye

