development:
  host: "localhost:3000"
  bucket: "drapertv-courses"
  access_key_id: 'AKIAIFAE3ZD3ELLSPKPQ'
  secret_access_key: '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'
test:
  access_key_id: 'AKIAIFAE3ZD3ELLSPKPQ'
  bucket: "drapertv-courses"
  secret_access_key: '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'

production:
  access_key_id: 'AKIAIFAE3ZD3ELLSPKPQ'
  bucket: "drapertv-courses"
  secret_access_key: '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'

staging:
  access_key_id: 'AKIAIFAE3ZD3ELLSPKPQ'
  bucket: "drapertv-courses"
  secret_access_key: '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'

